### ISSUE TITLE
Why is the MintableERC721Token contract even necessary?

### ISSUE THREAD

**Issue by roschler** [zeppelinos/basil#31]
In the Basil tutorial, one of the steps is the adding and proxying of the MintableERC721Token contract, to service the _MintableERC721Token_ property in the `BasilERC721` contract that was recently added to the app:

```sol
pragma solidity ^0.4.21;

import "./ERC721Token.sol";
import "../../ownership/Ownable.sol";

/**
 * @title Mintable ERC721 Token
 */
contract MintableERC721Token is Migratable, Ownable, ERC721Token {
  function initialize(address _sender, string _name, string _symbol) isInitializer("MintableERC721Token", "1.9.0")  public {
    Ownable.initialize(_sender);
    ERC721Token.initialize(_name, _symbol);
  }

  function mint(address _to, uint256 _tokenId) onlyOwner public {
    _mint(_to, _tokenId);
  }
}
```
Why is this contract even necessary?  All it does it pass through the `initialize` and `_mint` calls to the _ERC721Token_ code, if I understand the code correctly.  Why not just use the `ERC721Token` class directly?  

Also, why isn't the chaining '_mint' call made using the `super` keyword?  For example:

```super._mint(to, _tokenId);```

**Comment by facuspagnuolo** [comment]
Notice that we are calling `_mint` from `mint` it is not the same function. We are using this contract to have a public method for mintable functionality
